/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chat_delta_java_hello */

#ifndef _Included_chat_delta_java_hello
#define _Included_chat_delta_java_hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chat_delta_java_hello
 * Method:    sayHello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_chat_delta_java_hello_sayHello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
